availabel/urls.py
from django.urls import path ,include
from . import views


urlpatterns =[
    path('ProductList/',views.ProductList.as_view() ),
   # path('ProductList/<int:Product_id>/',views.FilterProductList.as_view() ),
     path('UserList/',views.UserList.as_view() ),

    ]

login/urls.py
from django.urls import path, include
from .  import views

app_name= 'accounts'
urlpatterns= [
    path('signup', views.signup_view , name='signup'),
    path('login', views.login_view , name='login'),
    path('logout', views.logout_view , name='logout'),


]

product/urls.py
from django.urls import path ,include
from . import views


app_name= 'product'
urlpatterns =[
    path('',views.index , name='list'),
    path('search/', views.SearchResultsView ,name='search' ),
    path('create/' , views.create_product, name='create'),
    path('order/', views.BoughterPanel ,name='order')


    ]

raham/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from availabel import views
from django.views.generic import TemplateView


urlpatterns = [

   path('', TemplateView.as_view(template_name="accounts/login.html")),
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('availabel/', include('availabel.urls')),
    path('accounts/',include('allauth.urls')),
    path('signup/' , include('login.urls')),

]

urlpatterns=format_suffix_patterns(urlpatterns)

availabel/models.py
from django.db import models
from product.models import Product

# Create your models here.

login/models.py
from django.contrib.auth.models import User
from django.db import models


class Token(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=48)

    def __unicode__(self):
        return "{}_token".format(self.user)

product/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField()
    explain = models.CharField(max_length=255)
    image_url = models.CharField(max_length=2083)


class Bought (models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    boughter = models.ForeignKey(User, on_delete=models.CASCADE)

product/forms.py
from django import forms
from . import models


class CreateProduct(forms.ModelForm):
    class Meta:
        model=models.Product
        fields= ['name','price','explain','image_url']

availabel/views.py
from django.http.response import JsonResponse
from rest_framework.views import  APIView
from product.models import Product
from django.contrib.auth.models import User
from .serializers import  ProductSerializer,UserSerializer


class UserList(APIView):
    queryset = User.objects.all()
    def get(self,request):
        persons =User.objects.all()
        serializer = UserSerializer(persons , many=True)
        return JsonResponse(serializer.data,safe=False)



class ProductList(APIView):
    queryset = Product.objects.all()
    def get(self,request):
        Shoes =Product.objects.all()
        serializer = ProductSerializer(Shoes , many=True)
        return JsonResponse(serializer.data,safe=False)


# class FilterProductList(APIView):
#     def get(self,request, **kwargs):
#       queryset = Product.objects.filter.get(id=kwargs['Product_id'])
#       serializer = ProductSerializer(queryset , many=True)
#       return JsonResponse(serializer.data,safe=False)

login/views.py
from django.shortcuts import  render,redirect
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django.contrib.auth import login ,logout


def signup_view(request):
    if request.method=='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request, user)
            return redirect('product:list')
        else:
            form = UserCreationForm()
    else:
        form=UserCreationForm()
    return render(request,'accounts/signup.html',{'form': form})


def login_view(request):
    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request,user)
            if 'nextpage' in request.POST:
                return redirect(request.POST.get('nextpage'))
            else:
                return redirect('product:list')
        else:
            form = AuthenticationForm()
    else:
        form=AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('product:list')

product/views.py
from django.db.models.query_utils import Q
from django.shortcuts import render,redirect
from django.views.decorators.csrf import csrf_exempt
from .models import Product
from django.contrib.auth.decorators import login_required
from . import forms


def index(request):
    products = Product.objects.all()
    return render(request, "index.html", {'product': products})



def SearchResultsView(request):
    query = request.GET.get('q')
    products = Product.objects.filter(Q(name__icontains=query))
    return render(request, "index.html", {'product': products})



@csrf_exempt
def BoughterPanel(request):
    # TODO check validation request
    context = {}
    context['product'] = request.GET['name']
    return render(request, 'order.html', context)


@login_required(login_url='accounts:login')
def create_product(request):
    if request.method == 'POST':
        form= forms.CreateProduct(request.POST)
        if form.is_valid():
            form.save()
            return redirect('product:list')
    else:
        form = forms.CreateProduct()
    return render(request, 'create_product.html',{'form':form})

login/templates/accounts/login.html
{% load socialaccount %}
{% providers_media_js %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Google Registration</title>
</head>
<body>
{% if user.is_authenticated %}
    <p>Welcome {{ user.username }} {{ user.email }}</p>
{#    <script>#}
{#        console.log("dsklhfskldfklshdfklhskldhfklshdklfhskdh",csrftoken);#}
{#        alert('token is : '+csrftoken);#}
{#    </script>#}
    <nav>
    <ul>
        <li>
            <form class="logout-link" method="post" action="{% url 'accounts:logout' %}">
                {% csrf_token %}
                <button type="submit">logout</button>
            </form>
        </li>
        <li>
             <a href="{% provider_login_url 'google' %}" style="background-color: lightskyblue"   >Login with another Google</a>

        </li>
{#        <li>#}
{#               <a href="signup" class="btn btn-primary" style="background-color: #fffccf">SignUp</a>#}
{#        </li>#}
        <li>
             <a href="product" class="btn btn-primary" style="background-color: #fffccf" >Display Product </a>
        </li>
    </ul>
    </nav>



  {% else %}
    <form action="{% url 'accounts:login' %}" method="post">
    {{ form }}
    {% csrf_token %}
        {% if request.GET.next %}
            <input type="hidden" name="nextpage" value="{{ request.GET.next }}">
        {% endif %}
    <input type="submit" value="login">
    </form>
 <a href="{%  url 'accounts:signup' %}" class="btn btn-primary" style="background-color: #fffccf">SignUp</a>
  <a href="{% provider_login_url 'google' %}" class="btn btn-primary">Login with Google</a>
  {% endif %}

<script>function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
const csrftoken = getCookie('csrftoken');</script>


</body>
</html>

login/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>signuppppppp</title>
</head>
<body>
<h1>signup</h1>
<form class="signup-form" method="post" action="">
{{ form }}
{% csrf_token %}
    <input value="submit" type="submit">
</form>
</body>
</html>

product/templates/create_product.html
{% extends 'base.html' %}
  {%  block content %}

  <nav  class="navbar navbar-light" style="background-color: #5b80b2;" >
 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'product:list' %}">Product list <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%  url 'product:create' %}">create new product</a>
      </li>

    </ul>
        </div>
</nav>

<h1>create product!</h1>
<form action="{% url 'product:create' %}" method="post" class="create-form">
{{ form }}
{% csrf_token %}
<input type="submit" value="created">
    </form>

{% endblock %}

product/templates/index.html
{% extends 'base.html' %}
    !-- Search form -->
{% block content %}

     <nav  class="navbar navbar-light" style="background-color: #5b80b2;" >

 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'product:list' %}">Product list <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%  url 'product:create' %}">create new product</a>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0" action="/product/search" method="GET">
      <input class="form-control mr-sm-2" type="search"  name='q' placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>


    <h1 dir="rtl" align="center">فروشگاه آنلاین</h1>
    <div class="row" style="margin-left: 100px;">
        {% for product in product %}
            <div class="card" style="width: 18rem; margin-top: 50px;">
                <img src="{{ product.image_url}}"  class="card-img-top" alt="..." style="width: 18rem; height: 20rem " >
                <div class="card-body">
                    <h5 class="card-title" dir="rtl" align="right">نام محصول : {{ product.name }}</h5>
                    <p class="card-text" dir="rtl" align="right">قیمت : {{ product.price }} ریال</p>
                    <p class="card-text" dir="rtl" align="right">توضیحات : {{ product.explain }} </p>
                    <a href="order?name={{ product.name }}" class="btn btn-primary" dir="rtl" align="right" methods="POST" onClick=>افزودن به سبد خرید</a>
                </div>
            </div>
            <div class="col"></div>

        {% endfor %}
    </div>


{% endblock %}

product/templates/order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>user : {{ user.username }}</p>
<p>  has bought {{ product }} product   </p>
</body>
</html>

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>Online Shoes Shop </title>
</head>
<body>
    {% block content %}

    {% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>
</html>